services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: safepix-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: safepix
      RABBITMQ_DEFAULT_PASS: safepix
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
