spring:
  application:
    name: SafePix Async
  rabbitmq:
    host: localhost
    port: 5672
    username: safepix
    password: safepix

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
